// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newBlacklist(db *gorm.DB, opts ...gen.DOOption) blacklist {
	_blacklist := blacklist{}

	_blacklist.blacklistDo.UseDB(db, opts...)
	_blacklist.blacklistDo.UseModel(&model.Blacklist{})

	tableName := _blacklist.blacklistDo.TableName()
	_blacklist.ALL = field.NewAsterisk(tableName)
	_blacklist.UserID = field.NewInt64(tableName, "user_id")
	_blacklist.CreatedAt = field.NewTime(tableName, "created_at")

	_blacklist.fillFieldMap()

	return _blacklist
}

type blacklist struct {
	blacklistDo blacklistDo

	ALL       field.Asterisk
	UserID    field.Int64 // QQ ç”¨æˆ· ID
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (b blacklist) Table(newTableName string) *blacklist {
	b.blacklistDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b blacklist) As(alias string) *blacklist {
	b.blacklistDo.DO = *(b.blacklistDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *blacklist) updateTableName(table string) *blacklist {
	b.ALL = field.NewAsterisk(table)
	b.UserID = field.NewInt64(table, "user_id")
	b.CreatedAt = field.NewTime(table, "created_at")

	b.fillFieldMap()

	return b
}

func (b *blacklist) WithContext(ctx context.Context) *blacklistDo {
	return b.blacklistDo.WithContext(ctx)
}

func (b blacklist) TableName() string { return b.blacklistDo.TableName() }

func (b blacklist) Alias() string { return b.blacklistDo.Alias() }

func (b blacklist) Columns(cols ...field.Expr) gen.Columns { return b.blacklistDo.Columns(cols...) }

func (b *blacklist) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *blacklist) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 2)
	b.fieldMap["user_id"] = b.UserID
	b.fieldMap["created_at"] = b.CreatedAt
}

func (b blacklist) clone(db *gorm.DB) blacklist {
	b.blacklistDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b blacklist) replaceDB(db *gorm.DB) blacklist {
	b.blacklistDo.ReplaceDB(db)
	return b
}

type blacklistDo struct{ gen.DO }

func (b blacklistDo) Debug() *blacklistDo {
	return b.withDO(b.DO.Debug())
}

func (b blacklistDo) WithContext(ctx context.Context) *blacklistDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b blacklistDo) ReadDB() *blacklistDo {
	return b.Clauses(dbresolver.Read)
}

func (b blacklistDo) WriteDB() *blacklistDo {
	return b.Clauses(dbresolver.Write)
}

func (b blacklistDo) Session(config *gorm.Session) *blacklistDo {
	return b.withDO(b.DO.Session(config))
}

func (b blacklistDo) Clauses(conds ...clause.Expression) *blacklistDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b blacklistDo) Returning(value interface{}, columns ...string) *blacklistDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b blacklistDo) Not(conds ...gen.Condition) *blacklistDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b blacklistDo) Or(conds ...gen.Condition) *blacklistDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b blacklistDo) Select(conds ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b blacklistDo) Where(conds ...gen.Condition) *blacklistDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b blacklistDo) Order(conds ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b blacklistDo) Distinct(cols ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b blacklistDo) Omit(cols ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b blacklistDo) Join(table schema.Tabler, on ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b blacklistDo) LeftJoin(table schema.Tabler, on ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b blacklistDo) RightJoin(table schema.Tabler, on ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b blacklistDo) Group(cols ...field.Expr) *blacklistDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b blacklistDo) Having(conds ...gen.Condition) *blacklistDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b blacklistDo) Limit(limit int) *blacklistDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b blacklistDo) Offset(offset int) *blacklistDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b blacklistDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *blacklistDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b blacklistDo) Unscoped() *blacklistDo {
	return b.withDO(b.DO.Unscoped())
}

func (b blacklistDo) Create(values ...*model.Blacklist) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b blacklistDo) CreateInBatches(values []*model.Blacklist, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b blacklistDo) Save(values ...*model.Blacklist) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b blacklistDo) First() (*model.Blacklist, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) Take() (*model.Blacklist, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) Last() (*model.Blacklist, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) Find() ([]*model.Blacklist, error) {
	result, err := b.DO.Find()
	return result.([]*model.Blacklist), err
}

func (b blacklistDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Blacklist, err error) {
	buf := make([]*model.Blacklist, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b blacklistDo) FindInBatches(result *[]*model.Blacklist, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b blacklistDo) Attrs(attrs ...field.AssignExpr) *blacklistDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b blacklistDo) Assign(attrs ...field.AssignExpr) *blacklistDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b blacklistDo) Joins(fields ...field.RelationField) *blacklistDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b blacklistDo) Preload(fields ...field.RelationField) *blacklistDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b blacklistDo) FirstOrInit() (*model.Blacklist, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) FirstOrCreate() (*model.Blacklist, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Blacklist), nil
	}
}

func (b blacklistDo) FindByPage(offset int, limit int) (result []*model.Blacklist, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b blacklistDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b blacklistDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b blacklistDo) Delete(models ...*model.Blacklist) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *blacklistDo) withDO(do gen.Dao) *blacklistDo {
	b.DO = *do.(*gen.DO)
	return b
}
