// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		Admin:              newAdmin(db, opts...),
		Blacklist:          newBlacklist(db, opts...),
		GroupJoinRequest:   newGroupJoinRequest(db, opts...),
		KnowledgeEntry:     newKnowledgeEntry(db, opts...),
		KnowledgeImportRun: newKnowledgeImportRun(db, opts...),
		ProcessedEvent:     newProcessedEvent(db, opts...),
		ScheduledJob:       newScheduledJob(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin              admin
	Blacklist          blacklist
	GroupJoinRequest   groupJoinRequest
	KnowledgeEntry     knowledgeEntry
	KnowledgeImportRun knowledgeImportRun
	ProcessedEvent     processedEvent
	ScheduledJob       scheduledJob
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Admin:              q.Admin.clone(db),
		Blacklist:          q.Blacklist.clone(db),
		GroupJoinRequest:   q.GroupJoinRequest.clone(db),
		KnowledgeEntry:     q.KnowledgeEntry.clone(db),
		KnowledgeImportRun: q.KnowledgeImportRun.clone(db),
		ProcessedEvent:     q.ProcessedEvent.clone(db),
		ScheduledJob:       q.ScheduledJob.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		Admin:              q.Admin.replaceDB(db),
		Blacklist:          q.Blacklist.replaceDB(db),
		GroupJoinRequest:   q.GroupJoinRequest.replaceDB(db),
		KnowledgeEntry:     q.KnowledgeEntry.replaceDB(db),
		KnowledgeImportRun: q.KnowledgeImportRun.replaceDB(db),
		ProcessedEvent:     q.ProcessedEvent.replaceDB(db),
		ScheduledJob:       q.ScheduledJob.replaceDB(db),
	}
}

type queryCtx struct {
	Admin              *adminDo
	Blacklist          *blacklistDo
	GroupJoinRequest   *groupJoinRequestDo
	KnowledgeEntry     *knowledgeEntryDo
	KnowledgeImportRun *knowledgeImportRunDo
	ProcessedEvent     *processedEventDo
	ScheduledJob       *scheduledJobDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:              q.Admin.WithContext(ctx),
		Blacklist:          q.Blacklist.WithContext(ctx),
		GroupJoinRequest:   q.GroupJoinRequest.WithContext(ctx),
		KnowledgeEntry:     q.KnowledgeEntry.WithContext(ctx),
		KnowledgeImportRun: q.KnowledgeImportRun.WithContext(ctx),
		ProcessedEvent:     q.ProcessedEvent.WithContext(ctx),
		ScheduledJob:       q.ScheduledJob.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
