// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newGroupJoinRequest(db *gorm.DB, opts ...gen.DOOption) groupJoinRequest {
	_groupJoinRequest := groupJoinRequest{}

	_groupJoinRequest.groupJoinRequestDo.UseDB(db, opts...)
	_groupJoinRequest.groupJoinRequestDo.UseModel(&model.GroupJoinRequest{})

	tableName := _groupJoinRequest.groupJoinRequestDo.TableName()
	_groupJoinRequest.ALL = field.NewAsterisk(tableName)
	_groupJoinRequest.ID = field.NewUint64(tableName, "id")
	_groupJoinRequest.RequestKey = field.NewString(tableName, "request_key")
	_groupJoinRequest.Flag = field.NewString(tableName, "flag")
	_groupJoinRequest.GroupID = field.NewInt64(tableName, "group_id")
	_groupJoinRequest.UserID = field.NewInt64(tableName, "user_id")
	_groupJoinRequest.StudentID = field.NewString(tableName, "student_id")
	_groupJoinRequest.StudentName = field.NewString(tableName, "student_name")
	_groupJoinRequest.SubType = field.NewString(tableName, "sub_type")
	_groupJoinRequest.Comment = field.NewString(tableName, "comment")
	_groupJoinRequest.Status = field.NewString(tableName, "status")
	_groupJoinRequest.Source = field.NewString(tableName, "source")
	_groupJoinRequest.RawJSON = field.NewString(tableName, "raw_json")
	_groupJoinRequest.RequestedAt = field.NewTime(tableName, "requested_at")
	_groupJoinRequest.FirstSeenAt = field.NewTime(tableName, "first_seen_at")
	_groupJoinRequest.LastSeenAt = field.NewTime(tableName, "last_seen_at")

	_groupJoinRequest.fillFieldMap()

	return _groupJoinRequest
}

type groupJoinRequest struct {
	groupJoinRequestDo groupJoinRequestDo

	ALL         field.Asterisk
	ID          field.Uint64
	RequestKey  field.String // ç¾¤ç”³è¯·åŽ»é‡é”®ï¼›ä¼˜å…ˆä½¿ç”¨ NapCat flag
	Flag        field.String // å¤„ç†ç¾¤ç”³è¯·æ—¶éœ€è¦çš„ flag
	GroupID     field.Int64  // QQç¾¤å·
	UserID      field.Int64  // ç”³è¯·äºº QQ
	StudentID   field.String // ç”³è¯·ä¿¡æ¯ä¸­æ˜¾å¼å¡«å†™çš„å­¦å·
	StudentName field.String // ç”³è¯·ä¿¡æ¯ä¸­æ˜¾å¼å¡«å†™çš„å§“å
	SubType     field.String // ç”³è¯·ç±»åž‹ï¼šadd/invite ç­‰
	Comment     field.String // ç”³è¯·éªŒè¯ä¿¡æ¯
	Status      field.String // ç™»è®°çŠ¶æ€ï¼špending/observed ç­‰
	Source      field.String // æ¥æºï¼ševent/system
	RawJSON     field.String // NapCat åŽŸå§‹äº‹ä»¶æˆ–ç³»ç»Ÿæ¶ˆæ¯ JSON
	RequestedAt field.Time   // ç”³è¯·æ—¶é—´
	FirstSeenAt field.Time   // é¦–æ¬¡ç™»è®°æ—¶é—´
	LastSeenAt  field.Time   // æœ€è¿‘å‡ºçŽ°æ—¶é—´

	fieldMap map[string]field.Expr
}

func (g groupJoinRequest) Table(newTableName string) *groupJoinRequest {
	g.groupJoinRequestDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g groupJoinRequest) As(alias string) *groupJoinRequest {
	g.groupJoinRequestDo.DO = *(g.groupJoinRequestDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *groupJoinRequest) updateTableName(table string) *groupJoinRequest {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.RequestKey = field.NewString(table, "request_key")
	g.Flag = field.NewString(table, "flag")
	g.GroupID = field.NewInt64(table, "group_id")
	g.UserID = field.NewInt64(table, "user_id")
	g.StudentID = field.NewString(table, "student_id")
	g.StudentName = field.NewString(table, "student_name")
	g.SubType = field.NewString(table, "sub_type")
	g.Comment = field.NewString(table, "comment")
	g.Status = field.NewString(table, "status")
	g.Source = field.NewString(table, "source")
	g.RawJSON = field.NewString(table, "raw_json")
	g.RequestedAt = field.NewTime(table, "requested_at")
	g.FirstSeenAt = field.NewTime(table, "first_seen_at")
	g.LastSeenAt = field.NewTime(table, "last_seen_at")

	g.fillFieldMap()

	return g
}

func (g *groupJoinRequest) WithContext(ctx context.Context) *groupJoinRequestDo {
	return g.groupJoinRequestDo.WithContext(ctx)
}

func (g groupJoinRequest) TableName() string { return g.groupJoinRequestDo.TableName() }

func (g groupJoinRequest) Alias() string { return g.groupJoinRequestDo.Alias() }

func (g groupJoinRequest) Columns(cols ...field.Expr) gen.Columns {
	return g.groupJoinRequestDo.Columns(cols...)
}

func (g *groupJoinRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *groupJoinRequest) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 15)
	g.fieldMap["id"] = g.ID
	g.fieldMap["request_key"] = g.RequestKey
	g.fieldMap["flag"] = g.Flag
	g.fieldMap["group_id"] = g.GroupID
	g.fieldMap["user_id"] = g.UserID
	g.fieldMap["student_id"] = g.StudentID
	g.fieldMap["student_name"] = g.StudentName
	g.fieldMap["sub_type"] = g.SubType
	g.fieldMap["comment"] = g.Comment
	g.fieldMap["status"] = g.Status
	g.fieldMap["source"] = g.Source
	g.fieldMap["raw_json"] = g.RawJSON
	g.fieldMap["requested_at"] = g.RequestedAt
	g.fieldMap["first_seen_at"] = g.FirstSeenAt
	g.fieldMap["last_seen_at"] = g.LastSeenAt
}

func (g groupJoinRequest) clone(db *gorm.DB) groupJoinRequest {
	g.groupJoinRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g groupJoinRequest) replaceDB(db *gorm.DB) groupJoinRequest {
	g.groupJoinRequestDo.ReplaceDB(db)
	return g
}

type groupJoinRequestDo struct{ gen.DO }

func (g groupJoinRequestDo) Debug() *groupJoinRequestDo {
	return g.withDO(g.DO.Debug())
}

func (g groupJoinRequestDo) WithContext(ctx context.Context) *groupJoinRequestDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupJoinRequestDo) ReadDB() *groupJoinRequestDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupJoinRequestDo) WriteDB() *groupJoinRequestDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupJoinRequestDo) Session(config *gorm.Session) *groupJoinRequestDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupJoinRequestDo) Clauses(conds ...clause.Expression) *groupJoinRequestDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupJoinRequestDo) Returning(value interface{}, columns ...string) *groupJoinRequestDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupJoinRequestDo) Not(conds ...gen.Condition) *groupJoinRequestDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupJoinRequestDo) Or(conds ...gen.Condition) *groupJoinRequestDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupJoinRequestDo) Select(conds ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupJoinRequestDo) Where(conds ...gen.Condition) *groupJoinRequestDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupJoinRequestDo) Order(conds ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupJoinRequestDo) Distinct(cols ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupJoinRequestDo) Omit(cols ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupJoinRequestDo) Join(table schema.Tabler, on ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupJoinRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupJoinRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupJoinRequestDo) Group(cols ...field.Expr) *groupJoinRequestDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupJoinRequestDo) Having(conds ...gen.Condition) *groupJoinRequestDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupJoinRequestDo) Limit(limit int) *groupJoinRequestDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupJoinRequestDo) Offset(offset int) *groupJoinRequestDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupJoinRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *groupJoinRequestDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupJoinRequestDo) Unscoped() *groupJoinRequestDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupJoinRequestDo) Create(values ...*model.GroupJoinRequest) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupJoinRequestDo) CreateInBatches(values []*model.GroupJoinRequest, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupJoinRequestDo) Save(values ...*model.GroupJoinRequest) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupJoinRequestDo) First() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) Take() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) Last() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) Find() ([]*model.GroupJoinRequest, error) {
	result, err := g.DO.Find()
	return result.([]*model.GroupJoinRequest), err
}

func (g groupJoinRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupJoinRequest, err error) {
	buf := make([]*model.GroupJoinRequest, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupJoinRequestDo) FindInBatches(result *[]*model.GroupJoinRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupJoinRequestDo) Attrs(attrs ...field.AssignExpr) *groupJoinRequestDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupJoinRequestDo) Assign(attrs ...field.AssignExpr) *groupJoinRequestDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupJoinRequestDo) Joins(fields ...field.RelationField) *groupJoinRequestDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupJoinRequestDo) Preload(fields ...field.RelationField) *groupJoinRequestDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupJoinRequestDo) FirstOrInit() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) FirstOrCreate() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) FindByPage(offset int, limit int) (result []*model.GroupJoinRequest, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupJoinRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupJoinRequestDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupJoinRequestDo) Delete(models ...*model.GroupJoinRequest) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupJoinRequestDo) withDO(do gen.Dao) *groupJoinRequestDo {
	g.DO = *do.(*gen.DO)
	return g
}
