// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newKnowledgeImportRun(db *gorm.DB, opts ...gen.DOOption) knowledgeImportRun {
	_knowledgeImportRun := knowledgeImportRun{}

	_knowledgeImportRun.knowledgeImportRunDo.UseDB(db, opts...)
	_knowledgeImportRun.knowledgeImportRunDo.UseModel(&model.KnowledgeImportRun{})

	tableName := _knowledgeImportRun.knowledgeImportRunDo.TableName()
	_knowledgeImportRun.ALL = field.NewAsterisk(tableName)
	_knowledgeImportRun.ID = field.NewUint64(tableName, "id")
	_knowledgeImportRun.Source = field.NewString(tableName, "source")
	_knowledgeImportRun.Status = field.NewString(tableName, "status")
	_knowledgeImportRun.TotalRows = field.NewInt64(tableName, "total_rows")
	_knowledgeImportRun.ImportedRows = field.NewInt64(tableName, "imported_rows")
	_knowledgeImportRun.SkippedRows = field.NewInt64(tableName, "skipped_rows")
	_knowledgeImportRun.ErrorMessage = field.NewString(tableName, "error_message")
	_knowledgeImportRun.StartedAt = field.NewTime(tableName, "started_at")
	_knowledgeImportRun.FinishedAt = field.NewTime(tableName, "finished_at")

	_knowledgeImportRun.fillFieldMap()

	return _knowledgeImportRun
}

type knowledgeImportRun struct {
	knowledgeImportRunDo knowledgeImportRunDo

	ALL          field.Asterisk
	ID           field.Uint64
	Source       field.String // å¯¼å…¥æ¥æºï¼Œå¦‚ wps
	Status       field.String // å¯¼å…¥çŠ¶æ€
	TotalRows    field.Int64  // æºè¡¨æ€»è¡Œæ•°
	ImportedRows field.Int64  // å¯¼å…¥æ¡æ•°
	SkippedRows  field.Int64  // è·³è¿‡æ¡æ•°
	ErrorMessage field.String // å¤±è´¥åŽŸå›
	StartedAt    field.Time   // å¼€å§‹æ—¶é—´
	FinishedAt   field.Time   // ç»“æŸæ—¶é—´

	fieldMap map[string]field.Expr
}

func (k knowledgeImportRun) Table(newTableName string) *knowledgeImportRun {
	k.knowledgeImportRunDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeImportRun) As(alias string) *knowledgeImportRun {
	k.knowledgeImportRunDo.DO = *(k.knowledgeImportRunDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeImportRun) updateTableName(table string) *knowledgeImportRun {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint64(table, "id")
	k.Source = field.NewString(table, "source")
	k.Status = field.NewString(table, "status")
	k.TotalRows = field.NewInt64(table, "total_rows")
	k.ImportedRows = field.NewInt64(table, "imported_rows")
	k.SkippedRows = field.NewInt64(table, "skipped_rows")
	k.ErrorMessage = field.NewString(table, "error_message")
	k.StartedAt = field.NewTime(table, "started_at")
	k.FinishedAt = field.NewTime(table, "finished_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgeImportRun) WithContext(ctx context.Context) *knowledgeImportRunDo {
	return k.knowledgeImportRunDo.WithContext(ctx)
}

func (k knowledgeImportRun) TableName() string { return k.knowledgeImportRunDo.TableName() }

func (k knowledgeImportRun) Alias() string { return k.knowledgeImportRunDo.Alias() }

func (k knowledgeImportRun) Columns(cols ...field.Expr) gen.Columns {
	return k.knowledgeImportRunDo.Columns(cols...)
}

func (k *knowledgeImportRun) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeImportRun) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 9)
	k.fieldMap["id"] = k.ID
	k.fieldMap["source"] = k.Source
	k.fieldMap["status"] = k.Status
	k.fieldMap["total_rows"] = k.TotalRows
	k.fieldMap["imported_rows"] = k.ImportedRows
	k.fieldMap["skipped_rows"] = k.SkippedRows
	k.fieldMap["error_message"] = k.ErrorMessage
	k.fieldMap["started_at"] = k.StartedAt
	k.fieldMap["finished_at"] = k.FinishedAt
}

func (k knowledgeImportRun) clone(db *gorm.DB) knowledgeImportRun {
	k.knowledgeImportRunDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeImportRun) replaceDB(db *gorm.DB) knowledgeImportRun {
	k.knowledgeImportRunDo.ReplaceDB(db)
	return k
}

type knowledgeImportRunDo struct{ gen.DO }

func (k knowledgeImportRunDo) Debug() *knowledgeImportRunDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeImportRunDo) WithContext(ctx context.Context) *knowledgeImportRunDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeImportRunDo) ReadDB() *knowledgeImportRunDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeImportRunDo) WriteDB() *knowledgeImportRunDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeImportRunDo) Session(config *gorm.Session) *knowledgeImportRunDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeImportRunDo) Clauses(conds ...clause.Expression) *knowledgeImportRunDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeImportRunDo) Returning(value interface{}, columns ...string) *knowledgeImportRunDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeImportRunDo) Not(conds ...gen.Condition) *knowledgeImportRunDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeImportRunDo) Or(conds ...gen.Condition) *knowledgeImportRunDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeImportRunDo) Select(conds ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeImportRunDo) Where(conds ...gen.Condition) *knowledgeImportRunDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeImportRunDo) Order(conds ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeImportRunDo) Distinct(cols ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeImportRunDo) Omit(cols ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeImportRunDo) Join(table schema.Tabler, on ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeImportRunDo) LeftJoin(table schema.Tabler, on ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeImportRunDo) RightJoin(table schema.Tabler, on ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeImportRunDo) Group(cols ...field.Expr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeImportRunDo) Having(conds ...gen.Condition) *knowledgeImportRunDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeImportRunDo) Limit(limit int) *knowledgeImportRunDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeImportRunDo) Offset(offset int) *knowledgeImportRunDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeImportRunDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *knowledgeImportRunDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeImportRunDo) Unscoped() *knowledgeImportRunDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeImportRunDo) Create(values ...*model.KnowledgeImportRun) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeImportRunDo) CreateInBatches(values []*model.KnowledgeImportRun, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeImportRunDo) Save(values ...*model.KnowledgeImportRun) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeImportRunDo) First() (*model.KnowledgeImportRun, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeImportRun), nil
	}
}

func (k knowledgeImportRunDo) Take() (*model.KnowledgeImportRun, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeImportRun), nil
	}
}

func (k knowledgeImportRunDo) Last() (*model.KnowledgeImportRun, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeImportRun), nil
	}
}

func (k knowledgeImportRunDo) Find() ([]*model.KnowledgeImportRun, error) {
	result, err := k.DO.Find()
	return result.([]*model.KnowledgeImportRun), err
}

func (k knowledgeImportRunDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeImportRun, err error) {
	buf := make([]*model.KnowledgeImportRun, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeImportRunDo) FindInBatches(result *[]*model.KnowledgeImportRun, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeImportRunDo) Attrs(attrs ...field.AssignExpr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeImportRunDo) Assign(attrs ...field.AssignExpr) *knowledgeImportRunDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeImportRunDo) Joins(fields ...field.RelationField) *knowledgeImportRunDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeImportRunDo) Preload(fields ...field.RelationField) *knowledgeImportRunDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeImportRunDo) FirstOrInit() (*model.KnowledgeImportRun, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeImportRun), nil
	}
}

func (k knowledgeImportRunDo) FirstOrCreate() (*model.KnowledgeImportRun, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeImportRun), nil
	}
}

func (k knowledgeImportRunDo) FindByPage(offset int, limit int) (result []*model.KnowledgeImportRun, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeImportRunDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeImportRunDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeImportRunDo) Delete(models ...*model.KnowledgeImportRun) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeImportRunDo) withDO(do gen.Dao) *knowledgeImportRunDo {
	k.DO = *do.(*gen.DO)
	return k
}
