// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newKnowledgeTriggerLog(db *gorm.DB, opts ...gen.DOOption) knowledgeTriggerLog {
	_knowledgeTriggerLog := knowledgeTriggerLog{}

	_knowledgeTriggerLog.knowledgeTriggerLogDo.UseDB(db, opts...)
	_knowledgeTriggerLog.knowledgeTriggerLogDo.UseModel(&model.KnowledgeTriggerLog{})

	tableName := _knowledgeTriggerLog.knowledgeTriggerLogDo.TableName()
	_knowledgeTriggerLog.ALL = field.NewAsterisk(tableName)
	_knowledgeTriggerLog.ID = field.NewUint64(tableName, "id")
	_knowledgeTriggerLog.SourceKey = field.NewString(tableName, "source_key")
	_knowledgeTriggerLog.TriggerType = field.NewString(tableName, "trigger_type")
	_knowledgeTriggerLog.GroupID = field.NewInt64(tableName, "group_id")
	_knowledgeTriggerLog.TriggeredAt = field.NewTime(tableName, "triggered_at")

	_knowledgeTriggerLog.fillFieldMap()

	return _knowledgeTriggerLog
}

type knowledgeTriggerLog struct {
	knowledgeTriggerLogDo knowledgeTriggerLogDo

	ALL         field.Asterisk
	ID          field.Uint64
	SourceKey   field.String // WPS 词条稳定键
	TriggerType field.String // keyword_reply 或 ai_retrieval
	GroupID     field.Int64  // 触发所在 QQ 群
	TriggeredAt field.Time

	fieldMap map[string]field.Expr
}

func (k knowledgeTriggerLog) Table(newTableName string) *knowledgeTriggerLog {
	k.knowledgeTriggerLogDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k knowledgeTriggerLog) As(alias string) *knowledgeTriggerLog {
	k.knowledgeTriggerLogDo.DO = *(k.knowledgeTriggerLogDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *knowledgeTriggerLog) updateTableName(table string) *knowledgeTriggerLog {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint64(table, "id")
	k.SourceKey = field.NewString(table, "source_key")
	k.TriggerType = field.NewString(table, "trigger_type")
	k.GroupID = field.NewInt64(table, "group_id")
	k.TriggeredAt = field.NewTime(table, "triggered_at")

	k.fillFieldMap()

	return k
}

func (k *knowledgeTriggerLog) WithContext(ctx context.Context) *knowledgeTriggerLogDo {
	return k.knowledgeTriggerLogDo.WithContext(ctx)
}

func (k knowledgeTriggerLog) TableName() string { return k.knowledgeTriggerLogDo.TableName() }

func (k knowledgeTriggerLog) Alias() string { return k.knowledgeTriggerLogDo.Alias() }

func (k knowledgeTriggerLog) Columns(cols ...field.Expr) gen.Columns {
	return k.knowledgeTriggerLogDo.Columns(cols...)
}

func (k *knowledgeTriggerLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *knowledgeTriggerLog) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 5)
	k.fieldMap["id"] = k.ID
	k.fieldMap["source_key"] = k.SourceKey
	k.fieldMap["trigger_type"] = k.TriggerType
	k.fieldMap["group_id"] = k.GroupID
	k.fieldMap["triggered_at"] = k.TriggeredAt
}

func (k knowledgeTriggerLog) clone(db *gorm.DB) knowledgeTriggerLog {
	k.knowledgeTriggerLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k knowledgeTriggerLog) replaceDB(db *gorm.DB) knowledgeTriggerLog {
	k.knowledgeTriggerLogDo.ReplaceDB(db)
	return k
}

type knowledgeTriggerLogDo struct{ gen.DO }

func (k knowledgeTriggerLogDo) Debug() *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Debug())
}

func (k knowledgeTriggerLogDo) WithContext(ctx context.Context) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k knowledgeTriggerLogDo) ReadDB() *knowledgeTriggerLogDo {
	return k.Clauses(dbresolver.Read)
}

func (k knowledgeTriggerLogDo) WriteDB() *knowledgeTriggerLogDo {
	return k.Clauses(dbresolver.Write)
}

func (k knowledgeTriggerLogDo) Session(config *gorm.Session) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Session(config))
}

func (k knowledgeTriggerLogDo) Clauses(conds ...clause.Expression) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k knowledgeTriggerLogDo) Returning(value interface{}, columns ...string) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k knowledgeTriggerLogDo) Not(conds ...gen.Condition) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k knowledgeTriggerLogDo) Or(conds ...gen.Condition) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k knowledgeTriggerLogDo) Select(conds ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k knowledgeTriggerLogDo) Where(conds ...gen.Condition) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k knowledgeTriggerLogDo) Order(conds ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k knowledgeTriggerLogDo) Distinct(cols ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k knowledgeTriggerLogDo) Omit(cols ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k knowledgeTriggerLogDo) Join(table schema.Tabler, on ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k knowledgeTriggerLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k knowledgeTriggerLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k knowledgeTriggerLogDo) Group(cols ...field.Expr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k knowledgeTriggerLogDo) Having(conds ...gen.Condition) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k knowledgeTriggerLogDo) Limit(limit int) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k knowledgeTriggerLogDo) Offset(offset int) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k knowledgeTriggerLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k knowledgeTriggerLogDo) Unscoped() *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Unscoped())
}

func (k knowledgeTriggerLogDo) Create(values ...*model.KnowledgeTriggerLog) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k knowledgeTriggerLogDo) CreateInBatches(values []*model.KnowledgeTriggerLog, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k knowledgeTriggerLogDo) Save(values ...*model.KnowledgeTriggerLog) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k knowledgeTriggerLogDo) First() (*model.KnowledgeTriggerLog, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeTriggerLog), nil
	}
}

func (k knowledgeTriggerLogDo) Take() (*model.KnowledgeTriggerLog, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeTriggerLog), nil
	}
}

func (k knowledgeTriggerLogDo) Last() (*model.KnowledgeTriggerLog, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeTriggerLog), nil
	}
}

func (k knowledgeTriggerLogDo) Find() ([]*model.KnowledgeTriggerLog, error) {
	result, err := k.DO.Find()
	return result.([]*model.KnowledgeTriggerLog), err
}

func (k knowledgeTriggerLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KnowledgeTriggerLog, err error) {
	buf := make([]*model.KnowledgeTriggerLog, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k knowledgeTriggerLogDo) FindInBatches(result *[]*model.KnowledgeTriggerLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k knowledgeTriggerLogDo) Attrs(attrs ...field.AssignExpr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k knowledgeTriggerLogDo) Assign(attrs ...field.AssignExpr) *knowledgeTriggerLogDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k knowledgeTriggerLogDo) Joins(fields ...field.RelationField) *knowledgeTriggerLogDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k knowledgeTriggerLogDo) Preload(fields ...field.RelationField) *knowledgeTriggerLogDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k knowledgeTriggerLogDo) FirstOrInit() (*model.KnowledgeTriggerLog, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeTriggerLog), nil
	}
}

func (k knowledgeTriggerLogDo) FirstOrCreate() (*model.KnowledgeTriggerLog, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KnowledgeTriggerLog), nil
	}
}

func (k knowledgeTriggerLogDo) FindByPage(offset int, limit int) (result []*model.KnowledgeTriggerLog, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k knowledgeTriggerLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k knowledgeTriggerLogDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k knowledgeTriggerLogDo) Delete(models ...*model.KnowledgeTriggerLog) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *knowledgeTriggerLogDo) withDO(do gen.Dao) *knowledgeTriggerLogDo {
	k.DO = *do.(*gen.DO)
	return k
}
