// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newProcessedEvent(db *gorm.DB, opts ...gen.DOOption) processedEvent {
	_processedEvent := processedEvent{}

	_processedEvent.processedEventDo.UseDB(db, opts...)
	_processedEvent.processedEventDo.UseModel(&model.ProcessedEvent{})

	tableName := _processedEvent.processedEventDo.TableName()
	_processedEvent.ALL = field.NewAsterisk(tableName)
	_processedEvent.EventKey = field.NewString(tableName, "event_key")
	_processedEvent.ProcessedAt = field.NewTime(tableName, "processed_at")

	_processedEvent.fillFieldMap()

	return _processedEvent
}

type processedEvent struct {
	processedEventDo processedEventDo

	ALL         field.Asterisk
	EventKey    field.String // äº‹ä»¶åŽ»é‡é”®
	ProcessedAt field.Time   // å¤„ç†æ—¶é—´ï¼›æ¸…ç†ä»»åŠ¡æŒ‰è¯¥å­—æ®µåˆ é™¤è¿‡æœŸè®°å½•

	fieldMap map[string]field.Expr
}

func (p processedEvent) Table(newTableName string) *processedEvent {
	p.processedEventDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p processedEvent) As(alias string) *processedEvent {
	p.processedEventDo.DO = *(p.processedEventDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *processedEvent) updateTableName(table string) *processedEvent {
	p.ALL = field.NewAsterisk(table)
	p.EventKey = field.NewString(table, "event_key")
	p.ProcessedAt = field.NewTime(table, "processed_at")

	p.fillFieldMap()

	return p
}

func (p *processedEvent) WithContext(ctx context.Context) *processedEventDo {
	return p.processedEventDo.WithContext(ctx)
}

func (p processedEvent) TableName() string { return p.processedEventDo.TableName() }

func (p processedEvent) Alias() string { return p.processedEventDo.Alias() }

func (p processedEvent) Columns(cols ...field.Expr) gen.Columns {
	return p.processedEventDo.Columns(cols...)
}

func (p *processedEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *processedEvent) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 2)
	p.fieldMap["event_key"] = p.EventKey
	p.fieldMap["processed_at"] = p.ProcessedAt
}

func (p processedEvent) clone(db *gorm.DB) processedEvent {
	p.processedEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p processedEvent) replaceDB(db *gorm.DB) processedEvent {
	p.processedEventDo.ReplaceDB(db)
	return p
}

type processedEventDo struct{ gen.DO }

func (p processedEventDo) Debug() *processedEventDo {
	return p.withDO(p.DO.Debug())
}

func (p processedEventDo) WithContext(ctx context.Context) *processedEventDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p processedEventDo) ReadDB() *processedEventDo {
	return p.Clauses(dbresolver.Read)
}

func (p processedEventDo) WriteDB() *processedEventDo {
	return p.Clauses(dbresolver.Write)
}

func (p processedEventDo) Session(config *gorm.Session) *processedEventDo {
	return p.withDO(p.DO.Session(config))
}

func (p processedEventDo) Clauses(conds ...clause.Expression) *processedEventDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p processedEventDo) Returning(value interface{}, columns ...string) *processedEventDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p processedEventDo) Not(conds ...gen.Condition) *processedEventDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p processedEventDo) Or(conds ...gen.Condition) *processedEventDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p processedEventDo) Select(conds ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p processedEventDo) Where(conds ...gen.Condition) *processedEventDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p processedEventDo) Order(conds ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p processedEventDo) Distinct(cols ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p processedEventDo) Omit(cols ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p processedEventDo) Join(table schema.Tabler, on ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p processedEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p processedEventDo) RightJoin(table schema.Tabler, on ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p processedEventDo) Group(cols ...field.Expr) *processedEventDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p processedEventDo) Having(conds ...gen.Condition) *processedEventDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p processedEventDo) Limit(limit int) *processedEventDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p processedEventDo) Offset(offset int) *processedEventDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p processedEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *processedEventDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p processedEventDo) Unscoped() *processedEventDo {
	return p.withDO(p.DO.Unscoped())
}

func (p processedEventDo) Create(values ...*model.ProcessedEvent) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p processedEventDo) CreateInBatches(values []*model.ProcessedEvent, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p processedEventDo) Save(values ...*model.ProcessedEvent) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p processedEventDo) First() (*model.ProcessedEvent, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProcessedEvent), nil
	}
}

func (p processedEventDo) Take() (*model.ProcessedEvent, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProcessedEvent), nil
	}
}

func (p processedEventDo) Last() (*model.ProcessedEvent, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProcessedEvent), nil
	}
}

func (p processedEventDo) Find() ([]*model.ProcessedEvent, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProcessedEvent), err
}

func (p processedEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProcessedEvent, err error) {
	buf := make([]*model.ProcessedEvent, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p processedEventDo) FindInBatches(result *[]*model.ProcessedEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p processedEventDo) Attrs(attrs ...field.AssignExpr) *processedEventDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p processedEventDo) Assign(attrs ...field.AssignExpr) *processedEventDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p processedEventDo) Joins(fields ...field.RelationField) *processedEventDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p processedEventDo) Preload(fields ...field.RelationField) *processedEventDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p processedEventDo) FirstOrInit() (*model.ProcessedEvent, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProcessedEvent), nil
	}
}

func (p processedEventDo) FirstOrCreate() (*model.ProcessedEvent, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProcessedEvent), nil
	}
}

func (p processedEventDo) FindByPage(offset int, limit int) (result []*model.ProcessedEvent, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p processedEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p processedEventDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p processedEventDo) Delete(models ...*model.ProcessedEvent) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *processedEventDo) withDO(do gen.Dao) *processedEventDo {
	p.DO = *do.(*gen.DO)
	return p
}
