// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/zjutjh/jxh-go/internal/storage/model"
)

func newScheduledJob(db *gorm.DB, opts ...gen.DOOption) scheduledJob {
	_scheduledJob := scheduledJob{}

	_scheduledJob.scheduledJobDo.UseDB(db, opts...)
	_scheduledJob.scheduledJobDo.UseModel(&model.ScheduledJob{})

	tableName := _scheduledJob.scheduledJobDo.TableName()
	_scheduledJob.ALL = field.NewAsterisk(tableName)
	_scheduledJob.ID = field.NewUint64(tableName, "id")
	_scheduledJob.Type = field.NewString(tableName, "type")
	_scheduledJob.TimeHhmm = field.NewString(tableName, "time_hhmm")
	_scheduledJob.GroupID = field.NewInt64(tableName, "group_id")
	_scheduledJob.Message = field.NewString(tableName, "message")
	_scheduledJob.Enabled = field.NewBool(tableName, "enabled")
	_scheduledJob.LastRunAt = field.NewTime(tableName, "last_run_at")
	_scheduledJob.CreatedAt = field.NewTime(tableName, "created_at")
	_scheduledJob.UpdatedAt = field.NewTime(tableName, "updated_at")

	_scheduledJob.fillFieldMap()

	return _scheduledJob
}

type scheduledJob struct {
	scheduledJobDo scheduledJobDo

	ALL       field.Asterisk
	ID        field.Uint64
	Type      field.String // 任务类型：每天/单次
	TimeHhmm  field.String // 触发时间，格式 HH:MM
	GroupID   field.Int64  // QQ群号
	Message   field.String // 定时发送内容
	Enabled   field.Bool   // 是否启用
	LastRunAt field.Time   // 最近执行时间；用于防止同一天重复触发
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (s scheduledJob) Table(newTableName string) *scheduledJob {
	s.scheduledJobDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s scheduledJob) As(alias string) *scheduledJob {
	s.scheduledJobDo.DO = *(s.scheduledJobDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *scheduledJob) updateTableName(table string) *scheduledJob {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.Type = field.NewString(table, "type")
	s.TimeHhmm = field.NewString(table, "time_hhmm")
	s.GroupID = field.NewInt64(table, "group_id")
	s.Message = field.NewString(table, "message")
	s.Enabled = field.NewBool(table, "enabled")
	s.LastRunAt = field.NewTime(table, "last_run_at")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *scheduledJob) WithContext(ctx context.Context) *scheduledJobDo {
	return s.scheduledJobDo.WithContext(ctx)
}

func (s scheduledJob) TableName() string { return s.scheduledJobDo.TableName() }

func (s scheduledJob) Alias() string { return s.scheduledJobDo.Alias() }

func (s scheduledJob) Columns(cols ...field.Expr) gen.Columns {
	return s.scheduledJobDo.Columns(cols...)
}

func (s *scheduledJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *scheduledJob) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["type"] = s.Type
	s.fieldMap["time_hhmm"] = s.TimeHhmm
	s.fieldMap["group_id"] = s.GroupID
	s.fieldMap["message"] = s.Message
	s.fieldMap["enabled"] = s.Enabled
	s.fieldMap["last_run_at"] = s.LastRunAt
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s scheduledJob) clone(db *gorm.DB) scheduledJob {
	s.scheduledJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s scheduledJob) replaceDB(db *gorm.DB) scheduledJob {
	s.scheduledJobDo.ReplaceDB(db)
	return s
}

type scheduledJobDo struct{ gen.DO }

func (s scheduledJobDo) Debug() *scheduledJobDo {
	return s.withDO(s.DO.Debug())
}

func (s scheduledJobDo) WithContext(ctx context.Context) *scheduledJobDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scheduledJobDo) ReadDB() *scheduledJobDo {
	return s.Clauses(dbresolver.Read)
}

func (s scheduledJobDo) WriteDB() *scheduledJobDo {
	return s.Clauses(dbresolver.Write)
}

func (s scheduledJobDo) Session(config *gorm.Session) *scheduledJobDo {
	return s.withDO(s.DO.Session(config))
}

func (s scheduledJobDo) Clauses(conds ...clause.Expression) *scheduledJobDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scheduledJobDo) Returning(value interface{}, columns ...string) *scheduledJobDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scheduledJobDo) Not(conds ...gen.Condition) *scheduledJobDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scheduledJobDo) Or(conds ...gen.Condition) *scheduledJobDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scheduledJobDo) Select(conds ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scheduledJobDo) Where(conds ...gen.Condition) *scheduledJobDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scheduledJobDo) Order(conds ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scheduledJobDo) Distinct(cols ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scheduledJobDo) Omit(cols ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scheduledJobDo) Join(table schema.Tabler, on ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scheduledJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scheduledJobDo) RightJoin(table schema.Tabler, on ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scheduledJobDo) Group(cols ...field.Expr) *scheduledJobDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scheduledJobDo) Having(conds ...gen.Condition) *scheduledJobDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scheduledJobDo) Limit(limit int) *scheduledJobDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scheduledJobDo) Offset(offset int) *scheduledJobDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scheduledJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *scheduledJobDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scheduledJobDo) Unscoped() *scheduledJobDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scheduledJobDo) Create(values ...*model.ScheduledJob) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scheduledJobDo) CreateInBatches(values []*model.ScheduledJob, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scheduledJobDo) Save(values ...*model.ScheduledJob) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scheduledJobDo) First() (*model.ScheduledJob, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScheduledJob), nil
	}
}

func (s scheduledJobDo) Take() (*model.ScheduledJob, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScheduledJob), nil
	}
}

func (s scheduledJobDo) Last() (*model.ScheduledJob, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScheduledJob), nil
	}
}

func (s scheduledJobDo) Find() ([]*model.ScheduledJob, error) {
	result, err := s.DO.Find()
	return result.([]*model.ScheduledJob), err
}

func (s scheduledJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ScheduledJob, err error) {
	buf := make([]*model.ScheduledJob, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scheduledJobDo) FindInBatches(result *[]*model.ScheduledJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scheduledJobDo) Attrs(attrs ...field.AssignExpr) *scheduledJobDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scheduledJobDo) Assign(attrs ...field.AssignExpr) *scheduledJobDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scheduledJobDo) Joins(fields ...field.RelationField) *scheduledJobDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scheduledJobDo) Preload(fields ...field.RelationField) *scheduledJobDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scheduledJobDo) FirstOrInit() (*model.ScheduledJob, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScheduledJob), nil
	}
}

func (s scheduledJobDo) FirstOrCreate() (*model.ScheduledJob, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ScheduledJob), nil
	}
}

func (s scheduledJobDo) FindByPage(offset int, limit int) (result []*model.ScheduledJob, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scheduledJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scheduledJobDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scheduledJobDo) Delete(models ...*model.ScheduledJob) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scheduledJobDo) withDO(do gen.Dao) *scheduledJobDo {
	s.DO = *do.(*gen.DO)
	return s
}
