// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdmin = "admins"

// Admin mapped from table <admins>
type Admin struct {
	GroupID       int64      `gorm:"column:group_id;type:bigint;primaryKey;comment:QQ 群 ID" json:"group_id"`                                    // QQ 群 ID
	UserID        int64      `gorm:"column:user_id;type:bigint;primaryKey;index:idx_admins_user_id,priority:1;comment:QQ 用户 ID" json:"user_id"` // QQ 用户 ID
	ManualGranted bool       `gorm:"column:manual_granted;type:tinyint(1);not null;default:0;comment:是否由当前群手动授权" json:"manual_granted"`         // 是否由当前群手动授权
	QQRole        string     `gorm:"column:qq_role;type:varchar(16);not null;default:member;comment:最近同步的 QQ 群角色" json:"qq_role"`               // 最近同步的 QQ 群角色
	CreatedAt     *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
