// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlacklist = "blacklists"

// Blacklist mapped from table <blacklists>
type Blacklist struct {
	UserID    int64      `gorm:"column:user_id;type:bigint;primaryKey;comment:QQ ç”¨æˆ· ID" json:"user_id"` // QQ ç”¨æˆ· ID
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
}

// TableName Blacklist's table name
func (*Blacklist) TableName() string {
	return TableNameBlacklist
}
