// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroupJoinRequest = "group_join_requests"

// GroupJoinRequest mapped from table <group_join_requests>
type GroupJoinRequest struct {
	ID          uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	RequestKey  string     `gorm:"column:request_key;type:varchar(191);not null;uniqueIndex:idx_group_join_requests_request_key,priority:1;comment:群申请业务去重键" json:"request_key"` // 群申请业务去重键
	Flag        *string    `gorm:"column:flag;type:varchar(512);comment:处理群申请时需要的 flag" json:"flag"`                                                                             // 处理群申请时需要的 flag
	GroupID     *int64     `gorm:"column:group_id;type:bigint;index:idx_group_join_requests_group_id,priority:1;comment:QQ群号" json:"group_id"`                                   // QQ群号
	UserID      *int64     `gorm:"column:user_id;type:bigint;index:idx_group_join_requests_user_id,priority:1;comment:申请人 QQ" json:"user_id"`                                    // 申请人 QQ
	StudentID   *string    `gorm:"column:student_id;type:varchar(64);comment:申请信息中显式填写的学号" json:"student_id"`                                                                    // 申请信息中显式填写的学号
	StudentName *string    `gorm:"column:student_name;type:varchar(64);comment:申请信息中显式填写的姓名" json:"student_name"`                                                                // 申请信息中显式填写的姓名
	SubType     *string    `gorm:"column:sub_type;type:varchar(32);comment:申请类型：add/invite 等" json:"sub_type"`                                                                   // 申请类型：add/invite 等
	Comment     *string    `gorm:"column:comment;type:text;comment:申请验证信息" json:"comment"`                                                                                       // 申请验证信息
	Status      string     `gorm:"column:status;type:varchar(32);not null;index:idx_group_join_requests_status,priority:1;comment:登记状态：pending/observed 等" json:"status"`        // 登记状态：pending/observed 等
	Source      string     `gorm:"column:source;type:varchar(32);not null;comment:来源：event/system" json:"source"`                                                                // 来源：event/system
	RawJSON     *string    `gorm:"column:raw_json;type:mediumtext;comment:NapCat 原始事件或系统消息 JSON" json:"raw_json"`                                                                // NapCat 原始事件或系统消息 JSON
	RequestedAt *time.Time `gorm:"column:requested_at;type:datetime(3);comment:申请时间" json:"requested_at"`                                                                        // 申请时间
	FirstSeenAt *time.Time `gorm:"column:first_seen_at;type:datetime(3);comment:首次登记时间" json:"first_seen_at"`                                                                    // 首次登记时间
	LastSeenAt  *time.Time `gorm:"column:last_seen_at;type:datetime(3);index:idx_group_join_requests_last_seen_at,priority:1;comment:最近出现时间" json:"last_seen_at"`                // 最近出现时间
}

// TableName GroupJoinRequest's table name
func (*GroupJoinRequest) TableName() string {
	return TableNameGroupJoinRequest
}
