// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGroupJoinRequest = "group_join_requests"

// GroupJoinRequest mapped from table <group_join_requests>
type GroupJoinRequest struct {
	ID          uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	RequestKey  string     `gorm:"column:request_key;type:varchar(191);not null;uniqueIndex:idx_group_join_requests_request_key,priority:1;comment:ç¾¤ç”³è¯·åŽ»é‡é”®ï¼›ä¼˜å…ˆä½¿ç”¨ NapCat flag" json:"request_key"` // ç¾¤ç”³è¯·åŽ»é‡é”®ï¼›ä¼˜å…ˆä½¿ç”¨ NapCat flag
	Flag        *string    `gorm:"column:flag;type:varchar(512);comment:å¤„ç†ç¾¤ç”³è¯·æ—¶éœ€è¦çš„ flag" json:"flag"`                                                                                                // å¤„ç†ç¾¤ç”³è¯·æ—¶éœ€è¦çš„ flag
	GroupID     *int64     `gorm:"column:group_id;type:bigint;index:idx_group_join_requests_group_id,priority:1;comment:QQç¾¤å·" json:"group_id"`                                                                    // QQç¾¤å·
	UserID      *int64     `gorm:"column:user_id;type:bigint;index:idx_group_join_requests_user_id,priority:1;comment:ç”³è¯·äºº QQ" json:"user_id"`                                                                   // ç”³è¯·äºº QQ
	StudentID   *string    `gorm:"column:student_id;type:varchar(64);comment:ç”³è¯·ä¿¡æ¯ä¸­æ˜¾å¼å¡«å†™çš„å­¦å·" json:"student_id"`                                                                                 // ç”³è¯·ä¿¡æ¯ä¸­æ˜¾å¼å¡«å†™çš„å­¦å·
	StudentName *string    `gorm:"column:student_name;type:varchar(64);comment:ç”³è¯·ä¿¡æ¯ä¸­æ˜¾å¼å¡«å†™çš„å§“å" json:"student_name"`                                                                             // ç”³è¯·ä¿¡æ¯ä¸­æ˜¾å¼å¡«å†™çš„å§“å
	SubType     *string    `gorm:"column:sub_type;type:varchar(32);comment:ç”³è¯·ç±»åž‹ï¼šadd/invite ç­‰" json:"sub_type"`                                                                                            // ç”³è¯·ç±»åž‹ï¼šadd/invite ç­‰
	Comment     *string    `gorm:"column:comment;type:text;comment:ç”³è¯·éªŒè¯ä¿¡æ¯" json:"comment"`                                                                                                                // ç”³è¯·éªŒè¯ä¿¡æ¯
	Status      string     `gorm:"column:status;type:varchar(32);not null;index:idx_group_join_requests_status,priority:1;comment:ç™»è®°çŠ¶æ€ï¼špending/observed ç­‰" json:"status"`                                 // ç™»è®°çŠ¶æ€ï¼špending/observed ç­‰
	Source      string     `gorm:"column:source;type:varchar(32);not null;comment:æ¥æºï¼ševent/system" json:"source"`                                                                                               // æ¥æºï¼ševent/system
	RawJSON     *string    `gorm:"column:raw_json;type:mediumtext;comment:NapCat åŽŸå§‹äº‹ä»¶æˆ–ç³»ç»Ÿæ¶ˆæ¯ JSON" json:"raw_json"`                                                                                   // NapCat åŽŸå§‹äº‹ä»¶æˆ–ç³»ç»Ÿæ¶ˆæ¯ JSON
	RequestedAt *time.Time `gorm:"column:requested_at;type:datetime(3);comment:ç”³è¯·æ—¶é—´" json:"requested_at"`                                                                                                     // ç”³è¯·æ—¶é—´
	FirstSeenAt *time.Time `gorm:"column:first_seen_at;type:datetime(3);comment:é¦–æ¬¡ç™»è®°æ—¶é—´" json:"first_seen_at"`                                                                                             // é¦–æ¬¡ç™»è®°æ—¶é—´
	LastSeenAt  *time.Time `gorm:"column:last_seen_at;type:datetime(3);index:idx_group_join_requests_last_seen_at,priority:1;comment:æœ€è¿‘å‡ºçŽ°æ—¶é—´" json:"last_seen_at"`                                         // æœ€è¿‘å‡ºçŽ°æ—¶é—´
}

// TableName GroupJoinRequest's table name
func (*GroupJoinRequest) TableName() string {
	return TableNameGroupJoinRequest
}
