// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKnowledgeEntry = "knowledge_entries"

// KnowledgeEntry mapped from table <knowledge_entries>
type KnowledgeEntry struct {
	ID                uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	SourceKey         string     `gorm:"column:source_key;type:varchar(255);not null;uniqueIndex:idx_knowledge_entries_source_key,priority:1;comment:çŸ¥è¯†æ¡ç›®ç¨³å®šé”®ï¼›WPS source_id ä¸ºç©ºæ—¶ç”± keyword è§„èŒƒåŒ–ç”Ÿæˆ" json:"source_key"` // çŸ¥è¯†æ¡ç›®ç¨³å®šé”®ï¼›WPS source_id ä¸ºç©ºæ—¶ç”± keyword è§„èŒƒåŒ–ç”Ÿæˆ
	Keyword           string     `gorm:"column:keyword;type:varchar(255);not null;comment:å…³é”®è¯ï¼›æ—§ WPS å›žå¤è¡¨ç¬¬ä¸€åˆ—" json:"keyword"`                                                                                                   // å…³é”®è¯ï¼›æ—§ WPS å›žå¤è¡¨ç¬¬ä¸€åˆ—
	EntryType         string     `gorm:"column:entry_type;type:varchar(32);not null;comment:æ¡ç›®ç±»åž‹ï¼šknowledge/menu_node/chitchat" json:"entry_type"`                                                                                         // æ¡ç›®ç±»åž‹ï¼šknowledge/menu_node/chitchat
	Path              *string    `gorm:"column:path;type:varchar(512);comment:ç”± %ç¼–å· èœå•æ ‘ç”Ÿæˆçš„èœå•è·¯å¾„" json:"path"`                                                                                                              // ç”± %ç¼–å· èœå•æ ‘ç”Ÿæˆçš„èœå•è·¯å¾„
	AliasesJSON       *string    `gorm:"column:aliases_json;type:json;comment:åŒä¹‰é—®æ³• JSON æ•°ç»„" json:"aliases_json"`                                                                                                                        // åŒä¹‰é—®æ³• JSON æ•°ç»„
	Category          *string    `gorm:"column:category;type:varchar(64);comment:åˆ†ç±»" json:"category"`                                                                                                                                           // åˆ†ç±»
	TagsJSON          *string    `gorm:"column:tags_json;type:json;comment:æ ‡ç­¾ JSON æ•°ç»„" json:"tags_json"`                                                                                                                                    // æ ‡ç­¾ JSON æ•°ç»„
	Answer            string     `gorm:"column:answer;type:text;not null;comment:æ ‡å‡†å›žç­”ï¼›æ—§ WPS å›žå¤è¡¨ç¬¬äºŒåˆ—" json:"answer"`                                                                                                          // æ ‡å‡†å›žç­”ï¼›æ—§ WPS å›žå¤è¡¨ç¬¬äºŒåˆ—
	Content           string     `gorm:"column:content;type:mediumtext;not null;comment:/ai æ£€ç´¢ä½¿ç”¨çš„çŸ¥è¯†æ­£æ–‡" json:"content"`                                                                                                            // /ai æ£€ç´¢ä½¿ç”¨çš„çŸ¥è¯†æ­£æ–‡
	Enabled           bool       `gorm:"column:enabled;type:tinyint(1);not null;comment:æ˜¯å¦å¯ç”¨" json:"enabled"`                                                                                                                               // æ˜¯å¦å¯ç”¨
	ExactReply        bool       `gorm:"column:exact_reply;type:tinyint(1);not null;comment:æ˜¯å¦å‚ä¸Žæ™®é€šå…³é”®è¯ç²¾ç¡®å›žå¤" json:"exact_reply"`                                                                                            // æ˜¯å¦å‚ä¸Žæ™®é€šå…³é”®è¯ç²¾ç¡®å›žå¤
	AiEnabled         bool       `gorm:"column:ai_enabled;type:tinyint(1);not null;comment:æ˜¯å¦å‚ä¸Ž /ai æ£€ç´¢" json:"ai_enabled"`                                                                                                              // æ˜¯å¦å‚ä¸Ž /ai æ£€ç´¢
	ContentHash       string     `gorm:"column:content_hash;type:varchar(64);not null;comment:content sha256ï¼Œç”¨äºŽåˆ¤æ–­å‘é‡æ˜¯å¦éœ€è¦é‡å»º" json:"content_hash"`                                                                           // content sha256ï¼Œç”¨äºŽåˆ¤æ–­å‘é‡æ˜¯å¦éœ€è¦é‡å»º
	VectorStatus      string     `gorm:"column:vector_status;type:varchar(16);not null;default:pending;comment:å‘é‡åŒæ­¥çŠ¶æ€ï¼špending/ready/failed" json:"vector_status"`                                                                     // å‘é‡åŒæ­¥çŠ¶æ€ï¼špending/ready/failed
	VectorContentHash *string    `gorm:"column:vector_content_hash;type:varchar(64);comment:å·²åŒæ­¥å‘é‡å¯¹åº”çš„ content_hash" json:"vector_content_hash"`                                                                                      // å·²åŒæ­¥å‘é‡å¯¹åº”çš„ content_hash
	VectorSyncedAt    *time.Time `gorm:"column:vector_synced_at;type:datetime(3);comment:å‘é‡åŒæ­¥æ—¶é—´" json:"vector_synced_at"`                                                                                                               // å‘é‡åŒæ­¥æ—¶é—´
	LastImportRunID   *uint64    `gorm:"column:last_import_run_id;type:bigint unsigned;comment:æœ€è¿‘ä¸€æ¬¡å¯¼å…¥æ‰¹æ¬¡ ID" json:"last_import_run_id"`                                                                                              // æœ€è¿‘ä¸€æ¬¡å¯¼å…¥æ‰¹æ¬¡ ID
	SourceUpdatedAt   *time.Time `gorm:"column:source_updated_at;type:datetime(3);comment:æºè¡¨äººå·¥ç»´æŠ¤æ—¶é—´" json:"source_updated_at"`                                                                                                       // æºè¡¨äººå·¥ç»´æŠ¤æ—¶é—´
	CreatedAt         *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName KnowledgeEntry's table name
func (*KnowledgeEntry) TableName() string {
	return TableNameKnowledgeEntry
}
