// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameKnowledgeTriggerLog = "knowledge_trigger_logs"

// KnowledgeTriggerLog mapped from table <knowledge_trigger_logs>
type KnowledgeTriggerLog struct {
	ID          uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	SourceKey   string    `gorm:"column:source_key;type:varchar(255);not null" json:"source_key"`
	TriggerType string    `gorm:"column:trigger_type;type:varchar(32);not null" json:"trigger_type"`
	GroupID     int64     `gorm:"column:group_id;type:bigint;not null" json:"group_id"`
	TriggeredAt time.Time `gorm:"column:triggered_at;type:datetime(3);not null" json:"triggered_at"`
}

func (*KnowledgeTriggerLog) TableName() string {
	return TableNameKnowledgeTriggerLog
}
