// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKnowledgeTriggerLog = "knowledge_trigger_logs"

// KnowledgeTriggerLog mapped from table <knowledge_trigger_logs>
type KnowledgeTriggerLog struct {
	ID          uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	SourceKey   string    `gorm:"column:source_key;type:varchar(255);not null;index:idx_trigger_stats,priority:2;comment:WPS 词条稳定键" json:"source_key"`                       // WPS 词条稳定键
	TriggerType string    `gorm:"column:trigger_type;type:varchar(32);not null;index:idx_trigger_stats,priority:3;comment:keyword_reply 或 ai_retrieval" json:"trigger_type"` // keyword_reply 或 ai_retrieval
	GroupID     int64     `gorm:"column:group_id;type:bigint;not null;comment:触发所在 QQ 群" json:"group_id"`                                                                    // 触发所在 QQ 群
	TriggeredAt time.Time `gorm:"column:triggered_at;type:datetime(3);not null;index:idx_trigger_stats,priority:1;default:CURRENT_TIMESTAMP(3)" json:"triggered_at"`
}

// TableName KnowledgeTriggerLog's table name
func (*KnowledgeTriggerLog) TableName() string {
	return TableNameKnowledgeTriggerLog
}
