// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKnowledgeImportRun = "knowledge_import_runs"

// KnowledgeImportRun mapped from table <knowledge_import_runs>
type KnowledgeImportRun struct {
	ID           uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Source       string     `gorm:"column:source;type:varchar(32);not null;comment:å¯¼å…¥æ¥æºï¼Œå¦‚ wps" json:"source"` // å¯¼å…¥æ¥æºï¼Œå¦‚ wps
	Status       string     `gorm:"column:status;type:varchar(16);not null;comment:å¯¼å…¥çŠ¶æ€" json:"status"`           // å¯¼å…¥çŠ¶æ€
	TotalRows    *int64     `gorm:"column:total_rows;type:bigint;comment:æºè¡¨æ€»è¡Œæ•°" json:"total_rows"`              // æºè¡¨æ€»è¡Œæ•°
	ImportedRows *int64     `gorm:"column:imported_rows;type:bigint;comment:å¯¼å…¥æ¡æ•°" json:"imported_rows"`           // å¯¼å…¥æ¡æ•°
	SkippedRows  *int64     `gorm:"column:skipped_rows;type:bigint;comment:è·³è¿‡æ¡æ•°" json:"skipped_rows"`             // è·³è¿‡æ¡æ•°
	ErrorMessage *string    `gorm:"column:error_message;type:text;comment:å¤±è´¥åŽŸå›" json:"error_message"`              // å¤±è´¥åŽŸå›
	StartedAt    *time.Time `gorm:"column:started_at;type:datetime(3);comment:å¼€å§‹æ—¶é—´" json:"started_at"`            // å¼€å§‹æ—¶é—´
	FinishedAt   *time.Time `gorm:"column:finished_at;type:datetime(3);comment:ç»“æŸæ—¶é—´" json:"finished_at"`          // ç»“æŸæ—¶é—´
}

// TableName KnowledgeImportRun's table name
func (*KnowledgeImportRun) TableName() string {
	return TableNameKnowledgeImportRun
}
