// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProcessedEvent = "processed_events"

// ProcessedEvent mapped from table <processed_events>
type ProcessedEvent struct {
	EventKey    string     `gorm:"column:event_key;type:varchar(128);primaryKey;comment:äº‹ä»¶åŽ»é‡é”®" json:"event_key"`                                                                                        // äº‹ä»¶åŽ»é‡é”®
	ProcessedAt *time.Time `gorm:"column:processed_at;type:datetime(3);index:idx_processed_events_processed_at,priority:1;comment:å¤„ç†æ—¶é—´ï¼›æ¸…ç†ä»»åŠ¡æŒ‰è¯¥å­—æ®µåˆ é™¤è¿‡æœŸè®°å½•" json:"processed_at"` // å¤„ç†æ—¶é—´ï¼›æ¸…ç†ä»»åŠ¡æŒ‰è¯¥å­—æ®µåˆ é™¤è¿‡æœŸè®°å½•
}

// TableName ProcessedEvent's table name
func (*ProcessedEvent) TableName() string {
	return TableNameProcessedEvent
}
