// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScheduledJob = "scheduled_jobs"

// ScheduledJob mapped from table <scheduled_jobs>
type ScheduledJob struct {
	ID        uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Type      string     `gorm:"column:type;type:varchar(16);not null;comment:任务类型：每天/单次" json:"type"`              // 任务类型：每天/单次
	TimeHhmm  string     `gorm:"column:time_hhmm;type:varchar(5);not null;comment:触发时间，格式 HH:MM" json:"time_hhmm"`  // 触发时间，格式 HH:MM
	GroupID   int64      `gorm:"column:group_id;type:bigint;not null;comment:QQ群号" json:"group_id"`                 // QQ群号
	Message   string     `gorm:"column:message;type:text;not null;comment:定时发送内容" json:"message"`                   // 定时发送内容
	Enabled   bool       `gorm:"column:enabled;type:tinyint(1);not null;comment:是否启用" json:"enabled"`               // 是否启用
	LastRunAt *time.Time `gorm:"column:last_run_at;type:datetime(3);comment:最近执行时间；用于防止同一天重复触发" json:"last_run_at"` // 最近执行时间；用于防止同一天重复触发
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName ScheduledJob's table name
func (*ScheduledJob) TableName() string {
	return TableNameScheduledJob
}
