// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScheduledJob = "scheduled_jobs"

// ScheduledJob mapped from table <scheduled_jobs>
type ScheduledJob struct {
	ID        uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Type      string     `gorm:"column:type;type:varchar(16);not null;comment:ä»»åŠ¡ç±»åž‹ï¼šæ¯å¤©/å•æ¬¡" json:"type"`                                // ä»»åŠ¡ç±»åž‹ï¼šæ¯å¤©/å•æ¬¡
	TimeHhmm  string     `gorm:"column:time_hhmm;type:varchar(5);not null;comment:è§¦å‘æ—¶é—´ï¼Œæ ¼å¼ HH:MM" json:"time_hhmm"`                        // è§¦å‘æ—¶é—´ï¼Œæ ¼å¼ HH:MM
	GroupID   int64      `gorm:"column:group_id;type:bigint;not null;comment:QQç¾¤å·" json:"group_id"`                                                 // QQç¾¤å·
	Message   string     `gorm:"column:message;type:text;not null;comment:å®šæ—¶å‘é€å†…å®¹" json:"message"`                                           // å®šæ—¶å‘é€å†…å®¹
	Enabled   bool       `gorm:"column:enabled;type:tinyint(1);not null;comment:æ˜¯å¦å¯ç”¨" json:"enabled"`                                           // æ˜¯å¦å¯ç”¨
	LastRunAt *time.Time `gorm:"column:last_run_at;type:datetime(3);comment:æœ€è¿‘æ‰§è¡Œæ—¶é—´ï¼›ç”¨äºŽé˜²æ­¢åŒä¸€å¤©é‡å¤è§¦å‘" json:"last_run_at"` // æœ€è¿‘æ‰§è¡Œæ—¶é—´ï¼›ç”¨äºŽé˜²æ­¢åŒä¸€å¤©é‡å¤è§¦å‘
	CreatedAt *time.Time `gorm:"column:created_at;type:datetime(3)" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime(3)" json:"updated_at"`
}

// TableName ScheduledJob's table name
func (*ScheduledJob) TableName() string {
	return TableNameScheduledJob
}
